# run: conda env create --prefix ./env --file environment.yml
name: benchmark-scarap
dependencies:
# scarap dependencies
- python=3.7 # only version that works with sonicparanoid v1.3.8
- pip
- bioconda::mafft
- bioconda::mmseqs2=15.*
# broccoli dependencies
- bioconda::diamond
# pangenome tools
- bioconda::orthofinder=2.5.2
- bioconda::sonicparanoid=1.3.8
- bioconda::pirate=1.0.5
- pip:
  # set exact versions of two sonicparanoid dependencies to avoid error
  - numpy==1.20.2
  - scikit-learn==0.24.1
  # scarap python package
  - git+https://github.com/swittouck/scarap.git@master
